// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrreu0NtXsdMHsaRj-Uim7UtrR4Dh9-uE',
    appId: '1:236972370773:web:43926621ce35a5e85c1ddc',
    messagingSenderId: '236972370773',
    projectId: 'thevetapp-fd704',
    authDomain: 'thevetapp-fd704.firebaseapp.com',
    storageBucket: 'thevetapp-fd704.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzYlqjKLgl_zdy9M8-8eUFB_qSNwP4oQg',
    appId: '1:236972370773:android:a63784d80d8e6b015c1ddc',
    messagingSenderId: '236972370773',
    projectId: 'thevetapp-fd704',
    storageBucket: 'thevetapp-fd704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHMXKEcVZoTcDxBDqoH10di-scANeCCTY',
    appId: '1:236972370773:ios:9f19766d2509783d5c1ddc',
    messagingSenderId: '236972370773',
    projectId: 'thevetapp-fd704',
    storageBucket: 'thevetapp-fd704.appspot.com',
    androidClientId: '236972370773-l0d14u8ncrf7996m1rng1buc5mfhi4fg.apps.googleusercontent.com',
    iosClientId: '236972370773-n4a96eia177hj8vel2b9l9ph4sank7ob.apps.googleusercontent.com',
    iosBundleId: 'com.example.theVetApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHMXKEcVZoTcDxBDqoH10di-scANeCCTY',
    appId: '1:236972370773:ios:14c33d0a9149210a5c1ddc',
    messagingSenderId: '236972370773',
    projectId: 'thevetapp-fd704',
    storageBucket: 'thevetapp-fd704.appspot.com',
    androidClientId: '236972370773-l0d14u8ncrf7996m1rng1buc5mfhi4fg.apps.googleusercontent.com',
    iosClientId: '236972370773-lcacca980cec4qqjh8qhbbg3fm8su4l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.theVetApp.RunnerTests',
  );
}
